nom: Opérations sur nombres décimaux - Produit d'un nombre entier et d'un décimal 
id: produit_entier_decimal
tags:
  - decimaux
  - Sixieme
headers_needed: 
  - correction
body: 
  script: produit_entier_decimal.py
  arguments: 
    template: assets/body_parts/exo_generique.tex